[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson
    knolleary/PubSubClient

; Upload via OTA: substitua pelo IP do ESP32 na sua rede
; Uso: pio run -e esp32dev-ota -t upload


; [env:esp32dev-ota]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200
; upload_protocol = espota
; upload_port = 192.168.89.228
; extra_scripts = pre:scripts/ota_auth.py

; lib_deps = bblanchon/ArduinoJson

